version: "3.7"

services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/html:/var/www/html
      - ./nginx/conf/wj.qq.com.key:/etc/nginx/wj.qq.com.key
      - ./nginx/conf/wj.qq.com.pem:/etc/nginx/wj.qq.com.pem
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/cond.f
      - ./nginx/logs:/var/log/nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      lnmp:
        ipv4_address: "6.6.0.10"
  redis:
    hostname: redis
    container_name: redis
    image: redis
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"
    networks:
      lnmp:
        ipv4_address: "6.6.0.20"
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/config:/etc/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: dbMagicAdmin
    networks:
      lnmp:
        ipv4_address: "6.6.0.30"
  php:
    hostname: php
    container_name: php
    build: .
    # image: "php:8.1.6-fpm"
    depends_on:
      - nginx
      - redis
      - mysql
    volumes:
      - ./nginx/html:/var/www/html
    command: php-fpm
    restart: always
    ports:
      - "9000:9000"
    networks:
      lnmp:
        ipv4_address: "6.6.0.60"

networks:
  lnmp:
    ipam:
      driver: default
      config:
        - subnet: "6.6.0.0/16"
